disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - line_length
  - todo
  - type_body_length
  - variable_name
  - type_name
  - nesting
  - conditional_binding_cascade
  - cyclomatic_complexity
included:
  - Source
  - NonProductionSource
